GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Alda Amorita Azza",
    "email": "aldaamorita@gmail.com",
    "password": "12345",
    "confPassword": "12345"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "aldaamorita@gmail.com",
    "password": "12345"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout